/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreationsRouteImport } from './routes/creations'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as ExpandRouteImport } from './routes/expand'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ImageToImageRouteImport } from './routes/image-to-image'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RemoveBackgroundRouteImport } from './routes/remove-background'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as UpscaleRouteImport } from './routes/upscale'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminGenerationsRouteImport } from './routes/admin.generations'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminModelsRouteImport } from './routes/admin.models'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiReadyRouteImport } from './routes/api.ready'
import { Route as BillingCancelRouteImport } from './routes/billing.cancel'
import { Route as BillingSuccessRouteImport } from './routes/billing.success'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ApiAssetsUploadRouteImport } from './routes/api.assets.upload'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'
import { Route as ApiAssetsLocalSplatRouteImport } from './routes/api.assets.local.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationsRoute = CreationsRouteImport.update({
  id: '/creations',
  path: '/creations',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpandRoute = ExpandRouteImport.update({
  id: '/expand',
  path: '/expand',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToImageRoute = ImageToImageRouteImport.update({
  id: '/image-to-image',
  path: '/image-to-image',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoveBackgroundRoute = RemoveBackgroundRouteImport.update({
  id: '/remove-background',
  path: '/remove-background',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const UpscaleRoute = UpscaleRouteImport.update({
  id: '/upscale',
  path: '/upscale',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGenerationsRoute = AdminGenerationsRouteImport.update({
  id: '/admin/generations',
  path: '/admin/generations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModelsRoute = AdminModelsRouteImport.update({
  id: '/admin/models',
  path: '/admin/models',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/admin/moderation',
  path: '/admin/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: '/api/ready',
  path: '/api/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCancelRoute = BillingCancelRouteImport.update({
  id: '/billing/cancel',
  path: '/billing/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ApiAssetsUploadRoute = ApiAssetsUploadRouteImport.update({
  id: '/api/assets/upload',
  path: '/api/assets/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsLocalSplatRoute = ApiAssetsLocalSplatRouteImport.update({
  id: '/api/assets/local/$',
  path: '/api/assets/local/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/creations': typeof CreationsRoute
  '/credits': typeof CreditsRoute
  '/editor': typeof EditorRoute
  '/expand': typeof ExpandRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/image-to-image': typeof ImageToImageRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/remove-background': typeof RemoveBackgroundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/upscale': typeof UpscaleRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/generations': typeof AdminGenerationsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/assets/upload': typeof ApiAssetsUploadRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/assets/local/$': typeof ApiAssetsLocalSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/creations': typeof CreationsRoute
  '/credits': typeof CreditsRoute
  '/editor': typeof EditorRoute
  '/expand': typeof ExpandRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/image-to-image': typeof ImageToImageRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/remove-background': typeof RemoveBackgroundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/upscale': typeof UpscaleRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/generations': typeof AdminGenerationsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/assets/upload': typeof ApiAssetsUploadRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/assets/local/$': typeof ApiAssetsLocalSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/creations': typeof CreationsRoute
  '/credits': typeof CreditsRoute
  '/editor': typeof EditorRoute
  '/expand': typeof ExpandRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/image-to-image': typeof ImageToImageRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/remove-background': typeof RemoveBackgroundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/upscale': typeof UpscaleRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/generations': typeof AdminGenerationsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/assets/upload': typeof ApiAssetsUploadRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/assets/local/$': typeof ApiAssetsLocalSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/creations'
    | '/credits'
    | '/editor'
    | '/expand'
    | '/explore'
    | '/favorites'
    | '/forgot-password'
    | '/history'
    | '/image-to-image'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/projects'
    | '/remove-background'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/studio'
    | '/upscale'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/generations'
    | '/admin/logs'
    | '/admin/models'
    | '/admin/moderation'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/users'
    | '/api/health'
    | '/api/ready'
    | '/billing/cancel'
    | '/billing/success'
    | '/projects/$projectId'
    | '/admin/'
    | '/api/assets/upload'
    | '/api/stripe/webhook'
    | '/api/assets/local/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/creations'
    | '/credits'
    | '/editor'
    | '/expand'
    | '/explore'
    | '/favorites'
    | '/forgot-password'
    | '/history'
    | '/image-to-image'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/projects'
    | '/remove-background'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/studio'
    | '/upscale'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/generations'
    | '/admin/logs'
    | '/admin/models'
    | '/admin/moderation'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/users'
    | '/api/health'
    | '/api/ready'
    | '/billing/cancel'
    | '/billing/success'
    | '/projects/$projectId'
    | '/admin'
    | '/api/assets/upload'
    | '/api/stripe/webhook'
    | '/api/assets/local/$'
  id:
    | '__root__'
    | '/'
    | '/creations'
    | '/credits'
    | '/editor'
    | '/expand'
    | '/explore'
    | '/favorites'
    | '/forgot-password'
    | '/history'
    | '/image-to-image'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/projects'
    | '/remove-background'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/studio'
    | '/upscale'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/generations'
    | '/admin/logs'
    | '/admin/models'
    | '/admin/moderation'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/users'
    | '/api/health'
    | '/api/ready'
    | '/billing/cancel'
    | '/billing/success'
    | '/projects/$projectId'
    | '/admin/'
    | '/api/assets/upload'
    | '/api/stripe/webhook'
    | '/api/assets/local/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreationsRoute: typeof CreationsRoute
  CreditsRoute: typeof CreditsRoute
  EditorRoute: typeof EditorRoute
  ExpandRoute: typeof ExpandRoute
  ExploreRoute: typeof ExploreRoute
  FavoritesRoute: typeof FavoritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  ImageToImageRoute: typeof ImageToImageRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RemoveBackgroundRoute: typeof RemoveBackgroundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StudioRoute: typeof StudioRoute
  UpscaleRoute: typeof UpscaleRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminGenerationsRoute: typeof AdminGenerationsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminModelsRoute: typeof AdminModelsRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReadyRoute: typeof ApiReadyRoute
  BillingCancelRoute: typeof BillingCancelRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAssetsUploadRoute: typeof ApiAssetsUploadRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiAssetsLocalSplatRoute: typeof ApiAssetsLocalSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creations': {
      id: '/creations'
      path: '/creations'
      fullPath: '/creations'
      preLoaderRoute: typeof CreationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expand': {
      id: '/expand'
      path: '/expand'
      fullPath: '/expand'
      preLoaderRoute: typeof ExpandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-image': {
      id: '/image-to-image'
      path: '/image-to-image'
      fullPath: '/image-to-image'
      preLoaderRoute: typeof ImageToImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remove-background': {
      id: '/remove-background'
      path: '/remove-background'
      fullPath: '/remove-background'
      preLoaderRoute: typeof RemoveBackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upscale': {
      id: '/upscale'
      path: '/upscale'
      fullPath: '/upscale'
      preLoaderRoute: typeof UpscaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/generations': {
      id: '/admin/generations'
      path: '/admin/generations'
      fullPath: '/admin/generations'
      preLoaderRoute: typeof AdminGenerationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/admin/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ready': {
      id: '/api/ready'
      path: '/api/ready'
      fullPath: '/api/ready'
      preLoaderRoute: typeof ApiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/cancel': {
      id: '/billing/cancel'
      path: '/billing/cancel'
      fullPath: '/billing/cancel'
      preLoaderRoute: typeof BillingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/api/assets/upload': {
      id: '/api/assets/upload'
      path: '/api/assets/upload'
      fullPath: '/api/assets/upload'
      preLoaderRoute: typeof ApiAssetsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/local/$': {
      id: '/api/assets/local/$'
      path: '/api/assets/local/$'
      fullPath: '/api/assets/local/$'
      preLoaderRoute: typeof ApiAssetsLocalSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreationsRoute: CreationsRoute,
  CreditsRoute: CreditsRoute,
  EditorRoute: EditorRoute,
  ExpandRoute: ExpandRoute,
  ExploreRoute: ExploreRoute,
  FavoritesRoute: FavoritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  ImageToImageRoute: ImageToImageRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RemoveBackgroundRoute: RemoveBackgroundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StudioRoute: StudioRoute,
  UpscaleRoute: UpscaleRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminGenerationsRoute: AdminGenerationsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminModelsRoute: AdminModelsRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiReadyRoute: ApiReadyRoute,
  BillingCancelRoute: BillingCancelRoute,
  BillingSuccessRoute: BillingSuccessRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAssetsUploadRoute: ApiAssetsUploadRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiAssetsLocalSplatRoute: ApiAssetsLocalSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
